[tools]
fd = "latest"
fzf = "latest"
ripgrep = "latest"
node = '24'
python = '3.14'
uv = "latest"

[env]
UV_PYTHON = { value = "{{ tools.python.path }}", tools = true }
UV_LINK_MODE = "copy"                                           # avoids hardlink issues across filesystems

[settings]
python.uv_venv_auto = "create|source"
trusted_config_paths = ["~/dots"]
