FROM alpine:latest

RUN apk update && apk add --no-cache git
# RUN git clone https://github.com/nefrob/dots /root/dotfiles

# WORKDIR /root/dotfiles
# RUN cd "$HOME/dots" && git checkout da7d5b57f8520243fbd276f0b906a4c94548742d
# RUN cd "$HOME/dots" && chmod +x packages/alpine.sh && ./packages/alpine.sh
# RUN cd "$HOME/dots" && chmod +x setup.sh && ./setup.sh
